/* 
 * Waitlisted API
 *
 * Waitlisted API
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SiteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SiteResponseTests
    {
        // TODO uncomment below to declare an instance variable for SiteResponse
        //private SiteResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SiteResponse
            //instance = new SiteResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SiteResponse
        /// </summary>
        [Test]
        public void SiteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SiteResponse
            //Assert.IsInstanceOfType<SiteResponse> (instance, "variable 'instance' is a SiteResponse");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'BrandColor'
        /// </summary>
        [Test]
        public void BrandColorTest()
        {
            // TODO unit test for the property 'BrandColor'
        }
        /// <summary>
        /// Test the property 'ButtonTextColor'
        /// </summary>
        [Test]
        public void ButtonTextColorTest()
        {
            // TODO unit test for the property 'ButtonTextColor'
        }
        /// <summary>
        /// Test the property 'CustomStyles'
        /// </summary>
        [Test]
        public void CustomStylesTest()
        {
            // TODO unit test for the property 'CustomStyles'
        }
        /// <summary>
        /// Test the property 'AskName'
        /// </summary>
        [Test]
        public void AskNameTest()
        {
            // TODO unit test for the property 'AskName'
        }
        /// <summary>
        /// Test the property 'SignupTitle'
        /// </summary>
        [Test]
        public void SignupTitleTest()
        {
            // TODO unit test for the property 'SignupTitle'
        }
        /// <summary>
        /// Test the property 'SignupCopy'
        /// </summary>
        [Test]
        public void SignupCopyTest()
        {
            // TODO unit test for the property 'SignupCopy'
        }
        /// <summary>
        /// Test the property 'PositionTitle'
        /// </summary>
        [Test]
        public void PositionTitleTest()
        {
            // TODO unit test for the property 'PositionTitle'
        }
        /// <summary>
        /// Test the property 'SocialCopy'
        /// </summary>
        [Test]
        public void SocialCopyTest()
        {
            // TODO unit test for the property 'SocialCopy'
        }
        /// <summary>
        /// Test the property 'SocialMessage'
        /// </summary>
        [Test]
        public void SocialMessageTest()
        {
            // TODO unit test for the property 'SocialMessage'
        }
        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Test]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'ShareSocialCopy'
        /// </summary>
        [Test]
        public void ShareSocialCopyTest()
        {
            // TODO unit test for the property 'ShareSocialCopy'
        }
        /// <summary>
        /// Test the property 'ReferralCopy'
        /// </summary>
        [Test]
        public void ReferralCopyTest()
        {
            // TODO unit test for the property 'ReferralCopy'
        }
        /// <summary>
        /// Test the property 'CheckPositionCopy'
        /// </summary>
        [Test]
        public void CheckPositionCopyTest()
        {
            // TODO unit test for the property 'CheckPositionCopy'
        }
        /// <summary>
        /// Test the property 'JoinButtonCopy'
        /// </summary>
        [Test]
        public void JoinButtonCopyTest()
        {
            // TODO unit test for the property 'JoinButtonCopy'
        }
        /// <summary>
        /// Test the property 'CheckReservationCopy'
        /// </summary>
        [Test]
        public void CheckReservationCopyTest()
        {
            // TODO unit test for the property 'CheckReservationCopy'
        }
        /// <summary>
        /// Test the property 'EmailFieldLabel'
        /// </summary>
        [Test]
        public void EmailFieldLabelTest()
        {
            // TODO unit test for the property 'EmailFieldLabel'
        }
        /// <summary>
        /// Test the property 'NameFieldLabel'
        /// </summary>
        [Test]
        public void NameFieldLabelTest()
        {
            // TODO unit test for the property 'NameFieldLabel'
        }
        /// <summary>
        /// Test the property 'ThankYouShareTemplate'
        /// </summary>
        [Test]
        public void ThankYouShareTemplateTest()
        {
            // TODO unit test for the property 'ThankYouShareTemplate'
        }
        /// <summary>
        /// Test the property 'WaitlistThreshold'
        /// </summary>
        [Test]
        public void WaitlistThresholdTest()
        {
            // TODO unit test for the property 'WaitlistThreshold'
        }
        /// <summary>
        /// Test the property 'UseCustomThankYou'
        /// </summary>
        [Test]
        public void UseCustomThankYouTest()
        {
            // TODO unit test for the property 'UseCustomThankYou'
        }
        /// <summary>
        /// Test the property 'HideWaitlist'
        /// </summary>
        [Test]
        public void HideWaitlistTest()
        {
            // TODO unit test for the property 'HideWaitlist'
        }
        /// <summary>
        /// Test the property 'UnmetSharedTemplate'
        /// </summary>
        [Test]
        public void UnmetSharedTemplateTest()
        {
            // TODO unit test for the property 'UnmetSharedTemplate'
        }
        /// <summary>
        /// Test the property 'ThresholdMet'
        /// </summary>
        [Test]
        public void ThresholdMetTest()
        {
            // TODO unit test for the property 'ThresholdMet'
        }
        /// <summary>
        /// Test the property 'WebsiteUrl'
        /// </summary>
        [Test]
        public void WebsiteUrlTest()
        {
            // TODO unit test for the property 'WebsiteUrl'
        }
        /// <summary>
        /// Test the property 'TrackingCode'
        /// </summary>
        [Test]
        public void TrackingCodeTest()
        {
            // TODO unit test for the property 'TrackingCode'
        }
        /// <summary>
        /// Test the property 'CustomCss'
        /// </summary>
        [Test]
        public void CustomCssTest()
        {
            // TODO unit test for the property 'CustomCss'
        }
        /// <summary>
        /// Test the property 'HideBranding'
        /// </summary>
        [Test]
        public void HideBrandingTest()
        {
            // TODO unit test for the property 'HideBranding'
        }
        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Test]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

    }

}
